version: '3.8'

services:
  zkbob-cloud:
    #image: ghcr.io/zkbob/zkbob-cloud-v2:${IMAGE_TAG:-main}
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: zkbob-cloud
    env_file: .env
    volumes:
      - ../params:/app/params/
      - ../data:/app/data/
      - ../configuration/${APP_ENVIRONMENT}.yaml:/app/configuration/config.yaml
    environment:
      CONFIG_FILE: /app/configuration/config.yaml
      RUST_LOG: info
      RUST_BACKTRACE: full
    ports:
      - 8001:8001
    restart: always

  zkbob-cloud-redis:
    image: redis:6.2.6
    container_name: zkbob-cloud-redis
    command: [redis-server]
    ports:
      - 8002:6379