# cloud service host
host: 0.0.0.0
# cloud service port
port: 8001
# path to transfer circuit params
transfer_params_path: "./params/transfer_params.bin"
# directory where the database will be created
db_path: "./data"
# relayer url
relayer_url: "https://relayer.thgkjlr.website"
# redis url
redis_url: "redis://zkbob-cloud-redis:6379"
# bearer token that should be used to access the admin api
admin_token: "123"
# gates precompute flag (reduces proving time but increases RAM consumption)
precompute: true

# configuration of the web3 client
web3:
  # rpc url
  provider_endpoint: "https://rpc.sepolia.org"
  # timeout for rpc requests
  provider_timeout_sec: 10
  # address of pool contract
  pool_address: "0x3bd088C19960A8B5d72E4e01847791BD0DD1C9E6"

# configuration of the worker responsible for computing proofs and sending prepared transactions to the relayer
send_worker:
  # maximum number of attempts in case of temporary errors
  max_attempts: 50
  # maximum number of parallel tasks
  max_parallel: 10
  # delay before processing a task
  queue_delay_sec: 0
  # interval between processing attempts
  queue_hidden_sec: 5

# configuration of the worker responsible for checking the status of sent transactions
status_worker:
  # maximum number of attempts in case of temporary errors
  max_attempts: 100
  # maximum number of parallel tasks
  max_parallel: 20
  # delay before processing a task
  queue_delay_sec: 5
  # interval between processing attempts
  queue_hidden_sec: 5

# configuration of logging
telemetry:
  kind: Stdout
  log_level: INFO
  service_name: zkbob-cloud

# these parameters will be overridden in build image workflow
version:
  ref_name: "main"
  commit_hash: "some_commit_hash"